#!/usr/bin/env node
// Builds the app's translation catalogs from the repository's gettext files.
//
// The core exports option labels, tooltips, categories and status messages as English
// msgids. This script collects every L("…") / _L("…") / _u8L("…") string in
// src/libslic3r, keeps only those entries from each localization/i18n/<lang>/*.po, and
// writes apps/orca/i18n/<lang>.json plus an index module with static requires (Metro
// needs them static). Run with `pnpm i18n` from mobile/.

import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repo = resolve(here, '..', '..')
const coreDir = join(repo, 'src', 'libslic3r')
const i18nDir = join(repo, 'localization', 'i18n')
const outDir = join(repo, 'mobile', 'apps', 'orca', 'i18n')

function* sourceFiles(dir) {
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry)
    if (statSync(path).isDirectory()) yield* sourceFiles(path)
    else if (/\.(cpp|hpp|h)$/.test(entry)) yield path
  }
}

// Decodes a C string literal body (between the quotes).
function decodeC(body) {
  return body.replace(/\\(x[0-9a-fA-F]{2}|.)/g, (_, e) => {
    switch (e[0]) {
      case 'n': return '\n'
      case 't': return '\t'
      case 'r': return '\r'
      case '"': return '"'
      case '\\': return '\\'
      case 'x': return String.fromCharCode(parseInt(e.slice(1), 16))
      default: return e
    }
  })
}

// Finds L("a" "b"), _L(...), _u8L(...) including adjacent literals across lines.
function extractStrings(text) {
  const out = new Set()
  const call = /(?<![A-Za-z0-9_])(?:_u8L|_L|L)\s*\(\s*/g
  let m
  while ((m = call.exec(text)) !== null) {
    let i = m.index + m[0].length
    let value = ''
    let found = false
    for (;;) {
      if (text[i] !== '"') break
      let j = i + 1
      let body = ''
      while (j < text.length && text[j] !== '"') {
        if (text[j] === '\\') { body += text[j] + text[j + 1]; j += 2 } else { body += text[j]; j++ }
      }
      value += decodeC(body)
      found = true
      i = j + 1
      while (i < text.length && /\s/.test(text[i])) i++
    }
    if (found && text[i] === ')' && value !== '') out.add(value)
  }
  return out
}

// Minimal PO reader: msgctxt / msgid / msgid_plural / msgstr[N] with multi-line strings.
function parsePo(text) {
  const entries = []
  let current = null
  let field = null
  const flush = () => { if (current !== null) entries.push(current); current = null; field = null }
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim()
    if (line === '') { flush(); continue }
    if (line.startsWith('#')) {
      if (current === null) current = { flags: '' }
      if (line.startsWith('#,')) current.flags += line
      continue
    }
    const kv = /^(msgctxt|msgid_plural|msgid|msgstr(?:\[\d+\])?)\s+"(.*)"$/.exec(line)
    if (kv !== null) {
      if (current === null) current = { flags: '' }
      field = kv[1]
      current[field] = decodeC(kv[2])
      continue
    }
    const cont = /^"(.*)"$/.exec(line)
    if (cont !== null && current !== null && field !== null) current[field] += decodeC(cont[1])
  }
  flush()
  return entries
}

const wanted = new Set()
for (const file of sourceFiles(coreDir)) for (const s of extractStrings(readFileSync(file, 'utf8'))) wanted.add(s)

mkdirSync(outDir, { recursive: true })
const languages = []
let total = 0
for (const lang of readdirSync(i18nDir).sort()) {
  const po = join(i18nDir, lang, `OrcaSlicer_${lang}.po`)
  let text
  try { text = readFileSync(po, 'utf8') } catch { continue }
  const catalog = {}
  for (const e of parsePo(text)) {
    if (e.msgid === undefined || e.msgid === '' || e.msgctxt !== undefined || e.msgid_plural !== undefined) continue
    if (e.flags.includes('fuzzy')) continue
    const str = e.msgstr
    if (str === undefined || str === '' || str === e.msgid) continue
    if (wanted.has(e.msgid)) catalog[e.msgid] = str
  }
  const count = Object.keys(catalog).length
  if (count === 0) continue
  writeFileSync(join(outDir, `${lang}.json`), JSON.stringify(catalog))
  languages.push(lang)
  total += count
}

const index = [
  '// Generated by mobile/scripts/i18n.mjs. Do not edit.',
  '',
  'export const catalogs: Record<string, () => Record<string, string>> = {',
  ...languages.map((l) => `  '${l}': () => require('./${l}.json') as Record<string, string>,`),
  '}',
  '',
]
writeFileSync(join(outDir, 'catalogs.ts'), index.join('\n'))
console.log(`${wanted.size} core strings; ${languages.length} languages, ${total} translations written to ${outDir}`)
